# Generated by Django 6.0.2 on 2026-02-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteimage',
            name='product_type',
            field=models.CharField(choices=[('TCI', 'Естественные цвета (True Color)'), ('NDVI', 'NDVI'), ('NDWI', 'NDWI')], max_length=10),
        ),
    ]
